version: '3'

services:
  db:
    container_name: db
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    restart: unless-stopped
